#!/bin/bash

#this part is lifted from gradle's bin script
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done

ROOT=$(dirname $PRG)
export JAVA_HOME="$ROOT/jre"

exec "$ROOT/bin/sly-chat"
